/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/me": {
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/users": {
    /** List Users */
    get: operations["list_users_api_v1_users_get"];
    /** Create User */
    post: operations["create_user_api_v1_users_post"];
  };
  "/api/v1/users/{user_id}": {
    /** Get User */
    get: operations["get_user_api_v1_users__user_id__get"];
  };
  "/api/v1/users/{user_id}/deactivate": {
    /** Deactivate User */
    post: operations["deactivate_user_api_v1_users__user_id__deactivate_post"];
  };
  "/api/v1/governorates": {
    /** List Governorates */
    get: operations["list_governorates_api_v1_governorates_get"];
  };
  "/api/v1/branches": {
    /** List Branches */
    get: operations["list_branches_api_v1_branches_get"];
    /** Create Branch */
    post: operations["create_branch_api_v1_branches_post"];
  };
  "/api/v1/territories": {
    /** List Territories */
    get: operations["list_territories_api_v1_territories_get"];
    /** Create Territory */
    post: operations["create_territory_api_v1_territories_post"];
  };
  "/api/v1/warehouses": {
    /** List Warehouses */
    get: operations["list_warehouses_api_v1_warehouses_get"];
    /** Create Warehouse */
    post: operations["create_warehouse_api_v1_warehouses_post"];
  };
  "/api/v1/custodies": {
    /** List Custodies */
    get: operations["list_custodies_api_v1_custodies_get"];
    /** Create Custody */
    post: operations["create_custody_api_v1_custodies_post"];
  };
  "/api/v1/custodies/{custody_id}/balance": {
    /** Custody Balance */
    get: operations["custody_balance_api_v1_custodies__custody_id__balance_get"];
  };
  "/api/v1/treasury/balance": {
    /** Treasury Balance */
    get: operations["treasury_balance_api_v1_treasury_balance_get"];
  };
  "/api/v1/ledger/entries": {
    /** List Ledger Entries */
    get: operations["list_ledger_entries_api_v1_ledger_entries_get"];
    /** Post Ledger Entry */
    post: operations["post_ledger_entry_api_v1_ledger_entries_post"];
  };
  "/api/v1/ledger/entries/{entry_id}/reverse": {
    /** Reverse Ledger Entry */
    post: operations["reverse_ledger_entry_api_v1_ledger_entries__entry_id__reverse_post"];
  };
  "/api/v1/customers": {
    /** List Customers */
    get: operations["list_customers_api_v1_customers_get"];
    /** Create Customer */
    post: operations["create_customer_api_v1_customers_post"];
  };
  "/api/v1/customers/{customer_id}": {
    /** Get Customer */
    get: operations["get_customer_api_v1_customers__customer_id__get"];
  };
  "/api/v1/customers/{customer_id}/reassign": {
    /** Reassign Customer */
    post: operations["reassign_customer_api_v1_customers__customer_id__reassign_post"];
  };
  "/api/v1/customers/{customer_id}/account": {
    /** Customer Account */
    get: operations["customer_account_api_v1_customers__customer_id__account_get"];
  };
  "/api/v1/audit": {
    /** List Audit */
    get: operations["list_audit_api_v1_audit_get"];
  };
  "/api/v1/items": {
    /** List Items */
    get: operations["list_items_api_v1_items_get"];
    /** Create Item */
    post: operations["create_item_api_v1_items_post"];
  };
  "/api/v1/items/{item_id}": {
    /** Update Item */
    patch: operations["update_item_api_v1_items__item_id__patch"];
  };
  "/api/v1/stock/on-hand": {
    /** Get On Hand */
    get: operations["get_on_hand_api_v1_stock_on_hand_get"];
  };
  "/api/v1/suppliers": {
    /** List Suppliers */
    get: operations["list_suppliers_api_v1_suppliers_get"];
    /** Create Supplier */
    post: operations["create_supplier_api_v1_suppliers_post"];
  };
  "/api/v1/suppliers/{supplier_id}/account": {
    /** Supplier Account */
    get: operations["supplier_account_api_v1_suppliers__supplier_id__account_get"];
  };
  "/api/v1/purchases": {
    /** Create Purchase */
    post: operations["create_purchase_api_v1_purchases_post"];
  };
  "/api/v1/purchases/{purchase_id}/returns": {
    /** Return Purchase */
    post: operations["return_purchase_api_v1_purchases__purchase_id__returns_post"];
  };
  "/api/v1/manufacturing/consume": {
    /** Consume */
    post: operations["consume_api_v1_manufacturing_consume_post"];
  };
  "/api/v1/manufacturing/produce": {
    /** Produce */
    post: operations["produce_api_v1_manufacturing_produce_post"];
  };
  "/api/v1/manufacturing/{op_id}/reverse": {
    /** Reverse */
    post: operations["reverse_api_v1_manufacturing__op_id__reverse_post"];
  };
  "/api/v1/sales": {
    /** Create Sale */
    post: operations["create_sale_api_v1_sales_post"];
  };
  "/api/v1/sales/{sale_id}": {
    /** Get Sale */
    get: operations["get_sale_api_v1_sales__sale_id__get"];
  };
  "/api/v1/sales/{sale_id}/returns": {
    /** Return Sale */
    post: operations["return_sale_api_v1_sales__sale_id__returns_post"];
  };
  "/api/v1/transfers": {
    /** Create Transfer */
    post: operations["create_transfer_api_v1_transfers_post"];
  };
  "/api/v1/transfers/{transfer_id}/approve": {
    /** Approve Transfer */
    post: operations["approve_transfer_api_v1_transfers__transfer_id__approve_post"];
  };
  "/api/v1/transfers/{transfer_id}/reverse": {
    /** Reverse Transfer */
    post: operations["reverse_transfer_api_v1_transfers__transfer_id__reverse_post"];
  };
  "/api/v1/settings/sales": {
    /** Get Sales Settings */
    get: operations["get_sales_settings_api_v1_settings_sales_get"];
    /** Update Sales Settings */
    put: operations["update_sales_settings_api_v1_settings_sales_put"];
  };
  "/api/v1/products/{item_id}/point-value": {
    /** Set Point Value */
    put: operations["set_point_value_api_v1_products__item_id__point_value_put"];
  };
  "/api/v1/loyalty/coupon-types": {
    /** List Types */
    get: operations["list_types_api_v1_loyalty_coupon_types_get"];
    /** Create Type */
    post: operations["create_type_api_v1_loyalty_coupon_types_post"];
  };
  "/api/v1/loyalty/coupon-types/{type_id}": {
    /** Update Type */
    patch: operations["update_type_api_v1_loyalty_coupon_types__type_id__patch"];
  };
  "/api/v1/customers/{customer_id}/points": {
    /** Get Balance */
    get: operations["get_balance_api_v1_customers__customer_id__points_get"];
  };
  "/api/v1/customers/{customer_id}/points/convert": {
    /** Convert */
    post: operations["convert_api_v1_customers__customer_id__points_convert_post"];
  };
  "/api/v1/coupons": {
    /** List Coupons */
    get: operations["list_coupons_api_v1_coupons_get"];
  };
  "/api/v1/coupons/{coupon_id}/redeem": {
    /** Redeem */
    post: operations["redeem_api_v1_coupons__coupon_id__redeem_post"];
  };
  "/api/v1/coupons/{coupon_id}/redemption/reverse": {
    /** Reverse Redemption */
    post: operations["reverse_redemption_api_v1_coupons__coupon_id__redemption_reverse_post"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AccountBalanceOut */
    AccountBalanceOut: {
      /** Account Id */
      account_id: number;
      /** Balance */
      balance: string;
      /**
       * Derived
       * @default true
       */
      derived?: boolean;
    };
    /** AuditOut */
    AuditOut: {
      /** Id */
      id: number;
      /** Actor User Id */
      actor_user_id: number | null;
      /** Action */
      action: string;
      /** Entity Type */
      entity_type: string | null;
      /** Entity Id */
      entity_id: number | null;
      /** Before */
      before: {
        [key: string]: unknown;
      } | null;
      /** After */
      after: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** BalanceOut */
    BalanceOut: {
      /** Account Id */
      account_id: number;
      /** Balance */
      balance: string;
    };
    /** BranchCreate */
    BranchCreate: {
      /** Name */
      name: string;
      /** Governorate Id */
      governorate_id: number;
      /**
       * Is Head Office
       * @default false
       */
      is_head_office?: boolean;
    };
    /** BranchOut */
    BranchOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Governorate Id */
      governorate_id: number;
      /** Is Head Office */
      is_head_office: boolean;
      /** Active */
      active: boolean;
    };
    /** ConvertRequest */
    ConvertRequest: {
      /** Coupon Type Ids */
      coupon_type_ids: number[];
    };
    /**
     * CouponKind
     * @enum {string}
     */
    CouponKind: "money" | "gift";
    /** CouponOut */
    CouponOut: {
      /** Id */
      id: number;
      /** Serial */
      serial: string;
      /** Customer Id */
      customer_id: number;
      /** Kind */
      kind: string;
      /** Value */
      value: string;
      /** Points Consumed */
      points_consumed: number;
      /** Status */
      status: string;
    };
    /**
     * CouponStatus
     * @enum {string}
     */
    CouponStatus: "issued" | "redeemed" | "voided";
    /** CouponTypeCreate */
    CouponTypeCreate: {
      /** Name */
      name: string;
      kind: components["schemas"]["CouponKind"];
      /** Point Cost */
      point_cost: number;
      /** Value */
      value: number | string;
    };
    /** CouponTypeOut */
    CouponTypeOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      kind: components["schemas"]["CouponKind"];
      /** Point Cost */
      point_cost: number;
      /** Value */
      value: string;
      /** Active */
      active: boolean;
    };
    /** CouponTypeUpdate */
    CouponTypeUpdate: {
      /** Name */
      name?: string | null;
      /** Point Cost */
      point_cost?: number | null;
      /** Value */
      value?: number | string | null;
      /** Active */
      active?: boolean | null;
    };
    /** CustodyCreate */
    CustodyCreate: {
      holder_type: components["schemas"]["HolderType"];
      /** Rep Id */
      rep_id?: number | null;
      /** Warehouse Id */
      warehouse_id?: number | null;
    };
    /** CustodyOut */
    CustodyOut: {
      /** Id */
      id: number;
      holder_type: components["schemas"]["HolderType"];
      /** Rep Id */
      rep_id: number | null;
      /** Warehouse Id */
      warehouse_id: number | null;
      /** Active */
      active: boolean;
    };
    /** CustomerAccountOut */
    CustomerAccountOut: {
      /** Id */
      id: number;
      /** Customer Id */
      customer_id: number;
      /** Account Id */
      account_id: number;
      /** Balance */
      balance: string;
      /**
       * Balance Derived
       * @default true
       */
      balance_derived?: boolean;
    };
    /** CustomerCreate */
    CustomerCreate: {
      /** Name */
      name: string;
      customer_type: components["schemas"]["CustomerType"];
      /** Rep Id */
      rep_id: number;
      /** Territory Id */
      territory_id: number;
      /** Phone */
      phone?: string | null;
    };
    /** CustomerCreated */
    CustomerCreated: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      customer_type: components["schemas"]["CustomerType"];
      /** Phone */
      phone: string | null;
      /** Rep Id */
      rep_id: number;
      /** Territory Id */
      territory_id: number;
      /** Active */
      active: boolean;
      /**
       * Duplicate Phone Customer Ids
       * @default []
       */
      duplicate_phone_customer_ids?: number[];
    };
    /** CustomerOut */
    CustomerOut: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      customer_type: components["schemas"]["CustomerType"];
      /** Phone */
      phone: string | null;
      /** Rep Id */
      rep_id: number;
      /** Territory Id */
      territory_id: number;
      /** Active */
      active: boolean;
    };
    /** CustomerReassign */
    CustomerReassign: {
      /** New Rep Id */
      new_rep_id: number;
      /** New Territory Id */
      new_territory_id: number;
    };
    /**
     * CustomerType
     * @enum {string}
     */
    CustomerType: "trader" | "plumber" | "other";
    /**
     * Direction
     * @enum {string}
     */
    Direction: "debit" | "credit";
    /** DocOut */
    DocOut: {
      /** Id */
      id: number;
      /** Document Number */
      document_number: string;
      /** Ledger Entry Id */
      ledger_entry_id?: number | null;
    };
    /** GovernorateOut */
    GovernorateOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HolderType
     * @enum {string}
     */
    HolderType: "rep" | "warehouse";
    /** ItemCreate */
    ItemCreate: {
      /** Name */
      name: string;
      kind: components["schemas"]["ItemKind"];
      /** Unit Of Measure */
      unit_of_measure: string;
      /** Purchase Price */
      purchase_price?: number | string | null;
      /** Sale Price */
      sale_price?: number | string | null;
    };
    /**
     * ItemKind
     * @enum {string}
     */
    ItemKind: "raw_material" | "product";
    /** ItemOut */
    ItemOut: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      kind: components["schemas"]["ItemKind"];
      /** Unit Of Measure */
      unit_of_measure: string;
      /** Purchase Price */
      purchase_price: string | null;
      /** Sale Price */
      sale_price: string | null;
      /** Active */
      active: boolean;
    };
    /** ItemUpdate */
    ItemUpdate: {
      /** Code */
      code?: string | null;
      /** Name */
      name?: string | null;
      /** Purchase Price */
      purchase_price?: number | string | null;
      /** Sale Price */
      sale_price?: number | string | null;
      /** Active */
      active?: boolean | null;
    };
    /** LedgerEntryCreate */
    LedgerEntryCreate: {
      /** Entry Type */
      entry_type: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /** Branch Id */
      branch_id?: number | null;
      /** Rep Id */
      rep_id?: number | null;
      /** Lines */
      lines: components["schemas"]["LineIn"][];
    };
    /** LedgerEntryOut */
    LedgerEntryOut: {
      /** Id */
      id: number;
      /** Entry Type */
      entry_type: string;
      /** Description */
      description: string;
      /** Actor User Id */
      actor_user_id: number;
      /** Rep Id */
      rep_id: number | null;
      /** Branch Id */
      branch_id: number | null;
      /** Reverses Entry Id */
      reverses_entry_id: number | null;
      /** Lines */
      lines: components["schemas"]["LineOut"][];
    };
    /** LineIn */
    LineIn: {
      /** Account Id */
      account_id: number;
      direction: components["schemas"]["Direction"];
      /** Amount */
      amount: number | string;
    };
    /** LineOut */
    LineOut: {
      /** Id */
      id: number;
      /** Account Id */
      account_id: number;
      direction: components["schemas"]["Direction"];
      /** Amount */
      amount: string;
    };
    /** LocationIn */
    LocationIn: {
      location_kind: components["schemas"]["LocationKind"];
      /** Location Id */
      location_id: number;
    };
    /**
     * LocationKind
     * @enum {string}
     */
    LocationKind: "warehouse" | "custody";
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** ManufactureOp */
    ManufactureOp: {
      /** Item Id */
      item_id: number;
      location: components["schemas"]["LocationIn"];
      /** Quantity */
      quantity: number | string;
    };
    /** OnHandOut */
    OnHandOut: {
      /** Item Id */
      item_id: number;
      location_kind: components["schemas"]["LocationKind"];
      /** Location Id */
      location_id: number;
      /** On Hand */
      on_hand: string;
      /**
       * Derived
       * @default true
       */
      derived?: boolean;
    };
    /** OpOut */
    OpOut: {
      /** Id */
      id: number;
      /** Document Number */
      document_number: string;
      /** Op Type */
      op_type: string;
      /** Stock Movement Id */
      stock_movement_id: number;
    };
    /** PointBalanceOut */
    PointBalanceOut: {
      /** Customer Id */
      customer_id: number;
      /** Balance */
      balance: number;
      /**
       * Derived
       * @default true
       */
      derived?: boolean;
    };
    /** PointValueBody */
    PointValueBody: {
      /** Point Value */
      point_value: number;
    };
    /** PointValueOut */
    PointValueOut: {
      /** Item Id */
      item_id: number;
      /** Point Value */
      point_value: number;
    };
    /** PurchaseCreate */
    PurchaseCreate: {
      /** Supplier Id */
      supplier_id: number;
      location: components["schemas"]["LocationIn"];
      /** Cash Amount */
      cash_amount: number | string;
      /** Credit Amount */
      credit_amount: number | string;
      /** Lines */
      lines: components["schemas"]["PurchaseLineIn"][];
    };
    /** PurchaseLineIn */
    PurchaseLineIn: {
      /** Item Id */
      item_id: number;
      /** Quantity */
      quantity: number | string;
      /** Unit Price */
      unit_price: number | string;
    };
    /** RedeemRequest */
    RedeemRequest: {
      mode: components["schemas"]["RedemptionMode"];
      /** Sales Invoice Id */
      sales_invoice_id?: number | null;
      /** Item Id */
      item_id?: number | null;
      location_kind?: components["schemas"]["LocationKind"] | null;
      /** Location Id */
      location_id?: number | null;
      /** Quantity */
      quantity?: number | string | null;
    };
    /**
     * RedemptionMode
     * @enum {string}
     */
    RedemptionMode: "money" | "gift_product" | "gift_money_off";
    /** RedemptionOut */
    RedemptionOut: {
      /** Id */
      id: number;
      /** Coupon Id */
      coupon_id: number;
      /** Mode */
      mode: string;
      /** Value */
      value: string;
      /** Ledger Entry Id */
      ledger_entry_id?: number | null;
      /** Stock Movement Id */
      stock_movement_id?: number | null;
      /** Coupon Status */
      coupon_status: string;
    };
    /** ReturnCreate */
    ReturnCreate: {
      /** Lines */
      lines: components["schemas"]["ReturnLineIn"][];
    };
    /** ReturnLineIn */
    ReturnLineIn: {
      /** Item Id */
      item_id: number;
      /** Quantity */
      quantity: number | string;
    };
    /**
     * RoleName
     * @enum {string}
     */
    RoleName: "system_admin" | "branch_manager" | "purchasing_manager" | "sales_manager" | "after_sales_staff" | "sales_rep";
    /** SaleCreate */
    SaleCreate: {
      /** Customer Id */
      customer_id: number;
      origin: components["schemas"]["LocationIn"];
      /**
       * Variable Discount Pct
       * @default 0
       */
      variable_discount_pct?: number | string;
      /** Cash Amount */
      cash_amount: number | string;
      /** Credit Amount */
      credit_amount: number | string;
      /** Lines */
      lines: components["schemas"]["SaleLineIn"][];
    };
    /** SaleLineIn */
    SaleLineIn: {
      /** Item Id */
      item_id: number;
      /** Quantity */
      quantity: number | string;
    };
    /** SalesInvoiceOut */
    SalesInvoiceOut: {
      /** Id */
      id: number;
      /** Document Number */
      document_number: string;
      /** Customer Id */
      customer_id: number;
      /** Gross */
      gross: string;
      /** Combined Pct */
      combined_pct: string;
      /** Net */
      net: string;
      /** Cash Amount */
      cash_amount: string;
      /** Credit Amount */
      credit_amount: string;
      /** Cash Account Id */
      cash_account_id: number;
      /** Ledger Entry Id */
      ledger_entry_id: number;
    };
    /** SalesSettingsBody */
    "SalesSettingsBody-Input": {
      /** Fixed Discount Pct */
      fixed_discount_pct: number | string;
    };
    /** SalesSettingsBody */
    "SalesSettingsBody-Output": {
      /** Fixed Discount Pct */
      fixed_discount_pct: string;
    };
    /** SupplierCreate */
    SupplierCreate: {
      /** Name */
      name: string;
      /** Phone */
      phone?: string | null;
    };
    /** SupplierOut */
    SupplierOut: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Phone */
      phone: string | null;
      /** Active */
      active: boolean;
    };
    /** TerritoryCreate */
    TerritoryCreate: {
      /** Name */
      name: string;
      /** Branch Id */
      branch_id: number;
    };
    /** TerritoryOut */
    TerritoryOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Branch Id */
      branch_id: number;
      /** Active */
      active: boolean;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
      /** Expires In */
      expires_in: number;
    };
    /** TransferCreate */
    TransferCreate: {
      /** Item Id */
      item_id: number;
      /** Quantity */
      quantity: number | string;
      route: components["schemas"]["TransferRoute"];
      source: components["schemas"]["LocationIn"];
      dest: components["schemas"]["LocationIn"];
    };
    /** TransferOut */
    TransferOut: {
      /** Id */
      id: number;
      /** Document Number */
      document_number: string;
      /** Status */
      status: string;
      /** Route */
      route: string;
      /** Approved By */
      approved_by?: number | null;
    };
    /**
     * TransferRoute
     * @enum {string}
     */
    TransferRoute: "central_to_branch" | "central_to_rep" | "rep_to_rep";
    /** UserCreate */
    UserCreate: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      role: components["schemas"]["RoleName"];
      /** Full Name */
      full_name: string;
      /** Branch Id */
      branch_id?: number | null;
      /** Territory Id */
      territory_id?: number | null;
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: number;
      /** Username */
      username: string;
      /** Role */
      role: string;
      /** Full Name */
      full_name: string;
      /** Branch Id */
      branch_id: number | null;
      /** Territory Id */
      territory_id: number | null;
      /** Active */
      active: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WarehouseCreate */
    WarehouseCreate: {
      /** Name */
      name: string;
      warehouse_type: components["schemas"]["WarehouseType"];
      /** Branch Id */
      branch_id?: number | null;
    };
    /** WarehouseOut */
    WarehouseOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      warehouse_type: components["schemas"]["WarehouseType"];
      /** Branch Id */
      branch_id: number | null;
      /** Active */
      active: boolean;
    };
    /**
     * WarehouseType
     * @enum {string}
     */
    WarehouseType: "central" | "branch";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Me */
  me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  /** List Users */
  list_users_api_v1_users_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"][];
        };
      };
    };
  };
  /** Create User */
  create_user_api_v1_users_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User */
  get_user_api_v1_users__user_id__get: {
    parameters: {
      path: {
        user_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Deactivate User */
  deactivate_user_api_v1_users__user_id__deactivate_post: {
    parameters: {
      path: {
        user_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Governorates */
  list_governorates_api_v1_governorates_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GovernorateOut"][];
        };
      };
    };
  };
  /** List Branches */
  list_branches_api_v1_branches_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BranchOut"][];
        };
      };
    };
  };
  /** Create Branch */
  create_branch_api_v1_branches_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BranchCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["BranchOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Territories */
  list_territories_api_v1_territories_get: {
    parameters: {
      query?: {
        branch_id?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TerritoryOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Territory */
  create_territory_api_v1_territories_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TerritoryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TerritoryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Warehouses */
  list_warehouses_api_v1_warehouses_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WarehouseOut"][];
        };
      };
    };
  };
  /** Create Warehouse */
  create_warehouse_api_v1_warehouses_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarehouseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["WarehouseOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Custodies */
  list_custodies_api_v1_custodies_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CustodyOut"][];
        };
      };
    };
  };
  /** Create Custody */
  create_custody_api_v1_custodies_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustodyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CustodyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Custody Balance */
  custody_balance_api_v1_custodies__custody_id__balance_get: {
    parameters: {
      path: {
        custody_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalanceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Treasury Balance */
  treasury_balance_api_v1_treasury_balance_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalanceOut"];
        };
      };
    };
  };
  /** List Ledger Entries */
  list_ledger_entries_api_v1_ledger_entries_get: {
    parameters: {
      query?: {
        account_id?: number | null;
        branch_id?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LedgerEntryOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post Ledger Entry */
  post_ledger_entry_api_v1_ledger_entries_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LedgerEntryCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["LedgerEntryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reverse Ledger Entry */
  reverse_ledger_entry_api_v1_ledger_entries__entry_id__reverse_post: {
    parameters: {
      path: {
        entry_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["LedgerEntryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Customers */
  list_customers_api_v1_customers_get: {
    parameters: {
      query?: {
        rep_id?: number | null;
        territory_id?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CustomerOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Customer */
  create_customer_api_v1_customers_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CustomerCreated"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Customer */
  get_customer_api_v1_customers__customer_id__get: {
    parameters: {
      path: {
        customer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CustomerOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reassign Customer */
  reassign_customer_api_v1_customers__customer_id__reassign_post: {
    parameters: {
      path: {
        customer_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerReassign"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CustomerOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Customer Account */
  customer_account_api_v1_customers__customer_id__account_get: {
    parameters: {
      path: {
        customer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CustomerAccountOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Audit */
  list_audit_api_v1_audit_get: {
    parameters: {
      query?: {
        actor_user_id?: number | null;
        action?: string | null;
        entity_type?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuditOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Items */
  list_items_api_v1_items_get: {
    parameters: {
      query?: {
        kind?: components["schemas"]["ItemKind"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ItemOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Item */
  create_item_api_v1_items_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Item */
  update_item_api_v1_items__item_id__patch: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get On Hand */
  get_on_hand_api_v1_stock_on_hand_get: {
    parameters: {
      query: {
        item_id: number;
        location_kind: components["schemas"]["LocationKind"];
        location_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OnHandOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Suppliers */
  list_suppliers_api_v1_suppliers_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierOut"][];
        };
      };
    };
  };
  /** Create Supplier */
  create_supplier_api_v1_suppliers_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SupplierOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Supplier Account */
  supplier_account_api_v1_suppliers__supplier_id__account_get: {
    parameters: {
      path: {
        supplier_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountBalanceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Purchase */
  create_purchase_api_v1_purchases_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PurchaseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["DocOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Return Purchase */
  return_purchase_api_v1_purchases__purchase_id__returns_post: {
    parameters: {
      path: {
        purchase_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReturnCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["DocOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Consume */
  consume_api_v1_manufacturing_consume_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManufactureOp"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["OpOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Produce */
  produce_api_v1_manufacturing_produce_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManufactureOp"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["OpOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reverse */
  reverse_api_v1_manufacturing__op_id__reverse_post: {
    parameters: {
      path: {
        op_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["OpOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Sale */
  create_sale_api_v1_sales_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SalesInvoiceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Sale */
  get_sale_api_v1_sales__sale_id__get: {
    parameters: {
      path: {
        sale_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesInvoiceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Return Sale */
  return_sale_api_v1_sales__sale_id__returns_post: {
    parameters: {
      path: {
        sale_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReturnCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Transfer */
  create_transfer_api_v1_transfers_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TransferOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Approve Transfer */
  approve_transfer_api_v1_transfers__transfer_id__approve_post: {
    parameters: {
      path: {
        transfer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TransferOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reverse Transfer */
  reverse_transfer_api_v1_transfers__transfer_id__reverse_post: {
    parameters: {
      path: {
        transfer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TransferOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Sales Settings */
  get_sales_settings_api_v1_settings_sales_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesSettingsBody-Output"];
        };
      };
    };
  };
  /** Update Sales Settings */
  update_sales_settings_api_v1_settings_sales_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesSettingsBody-Input"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesSettingsBody-Output"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Set Point Value */
  set_point_value_api_v1_products__item_id__point_value_put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PointValueBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PointValueOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Types */
  list_types_api_v1_loyalty_coupon_types_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CouponTypeOut"][];
        };
      };
    };
  };
  /** Create Type */
  create_type_api_v1_loyalty_coupon_types_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CouponTypeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CouponTypeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Type */
  update_type_api_v1_loyalty_coupon_types__type_id__patch: {
    parameters: {
      path: {
        type_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CouponTypeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CouponTypeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Balance */
  get_balance_api_v1_customers__customer_id__points_get: {
    parameters: {
      path: {
        customer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PointBalanceOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Convert */
  convert_api_v1_customers__customer_id__points_convert_post: {
    parameters: {
      path: {
        customer_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConvertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CouponOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Coupons */
  list_coupons_api_v1_coupons_get: {
    parameters: {
      query?: {
        customer_id?: number | null;
        status_filter?: components["schemas"]["CouponStatus"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CouponOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Redeem */
  redeem_api_v1_coupons__coupon_id__redeem_post: {
    parameters: {
      path: {
        coupon_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RedeemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["RedemptionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reverse Redemption */
  reverse_redemption_api_v1_coupons__coupon_id__redemption_reverse_post: {
    parameters: {
      path: {
        coupon_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["RedemptionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
