"""استلام الكوبونات من العملاء router.

Built for the rep's phone as much as the office screen: one endpoint to check a serial as it is
typed or scanned, one to post the handover, and an idempotency key so a receipt queued offline
and retried on a flaky connection lands once.
"""
from __future__ import annotations

from datetime import date
from decimal import Decimal

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from src.auth.dependencies import CurrentUser, require_capability
from src.auth.rbac import CAP_COUPON_RECEIVE
from src.core.db import get_db
from src.models.role import RoleName
from src.auth import branch_scope
from src.services import coupon_receipt_service
from src.services.coupon_receipt_service import CouponReceiptError

router = APIRouter(tags=["coupon-receipts"], prefix="/coupon-receipts")


class ReceiptIn(BaseModel):
    """Either an explicit list of serials, or a range to expand — whichever the rep has."""

    serials: list[str] = []
    serial_from: str | None = None
    serial_to: str | None = None
    customer_id: int | None = None
    rep_user_id: int | None = None
    received_date: date | None = None
    notes: str | None = None
    # اللي المندوب قاله عن النوع والقيمة — بيتخزن زي ما هو، والسيرفر بيفضل يتحقق من السريالات.
    declared_kind: str | None = None
    declared_value: Decimal | None = None
    customer_type: str | None = None
    # Generated by the app per queued receipt so a retry cannot post it twice.
    client_uuid: str | None = None


class ReceiptLineOut(BaseModel):
    id: int
    serial: str
    sales_invoice_id: int


class ReceiptOut(BaseModel):
    id: int
    document_number: str
    customer_id: int | None
    rep_user_id: int | None
    received_date: date | None
    coupon_count: int
    notes: str | None
    lines: list[ReceiptLineOut] = []


def _out(r) -> ReceiptOut:
    return ReceiptOut(
        id=r.id, document_number=r.document_number, customer_id=r.customer_id,
        rep_user_id=r.rep_user_id, received_date=r.received_date,
        coupon_count=r.coupon_count, notes=r.notes,
        lines=[ReceiptLineOut(id=ln.id, serial=ln.serial,
                              sales_invoice_id=ln.sales_invoice_id) for ln in r.lines],
    )


@router.get("/check", response_model=dict)
def check_serial(
    serial: str = Query(..., description="The number written on the coupon"),
    _: CurrentUser = Depends(require_capability(CAP_COUPON_RECEIVE)),
    db: Session = Depends(get_db),
) -> dict:
    """فحص كوبون — was this serial ever issued, to whom, and has it already come back?

    The app calls this per coupon as it is typed, so the rep learns a coupon is bad while the
    customer is still standing there rather than after the handover is posted.
    """
    return coupon_receipt_service.check_serial(db, serial)


@router.get("/issued-to/{customer_id}", response_model=list[dict])
def coupons_issued_to(
    customer_id: int,
    _: CurrentUser = Depends(require_capability(CAP_COUPON_RECEIVE)),
    db: Session = Depends(get_db),
) -> list[dict]:
    """The books this customer was handed, and how much of each is still out.

    A return screen asks this before it will take a coupon back: he can only return what he was
    given. Offering a free box and checking afterwards means finding out at the end of a document
    that half of it cannot be saved, with the customer still at the counter.
    """
    return coupon_receipt_service.issued_to_customer(db, customer_id)


@router.post("", response_model=ReceiptOut, status_code=status.HTTP_201_CREATED)
def create_receipt(
    body: ReceiptIn,
    current: CurrentUser = Depends(require_capability(CAP_COUPON_RECEIVE)),
    db: Session = Depends(get_db),
) -> ReceiptOut:
    """استلام كوبونات — all of them or none: one bad coupon fails the whole handover."""
    try:
        serials = list(body.serials)
        if body.serial_from:
            serials.extend(coupon_receipt_service.expand_range(body.serial_from, body.serial_to))
        receipt = coupon_receipt_service.create_receipt(
            db, serials=serials, actor_user_id=current.id, customer_id=body.customer_id,
            # A rep receiving coupons is the rep on the document unless someone says otherwise.
            rep_user_id=body.rep_user_id if body.rep_user_id is not None else (
                current.id if current.role == RoleName.sales_rep else None),
            received_date=body.received_date, notes=body.notes, client_uuid=body.client_uuid,
            declared_kind=body.declared_kind, declared_value=body.declared_value,
            customer_type=body.customer_type,
        )
    except CouponReceiptError as exc:
        raise HTTPException(422, {"code": "coupon_invalid", "message": str(exc)}) from exc
    out = _out(receipt)
    db.commit()
    return out


@router.get("", response_model=list[ReceiptOut])
def list_receipts(
    customer_id: int | None = Query(None),
    rep_user_id: int | None = Query(None),
    current: CurrentUser = Depends(require_capability(CAP_COUPON_RECEIVE)),
    db: Session = Depends(get_db),
) -> list[ReceiptOut]:
    # A rep sees his own handovers, not the branch's.
    scope_rep = current.id if current.role == RoleName.sales_rep else rep_user_id
    rows = coupon_receipt_service.list_receipts(
        db, customer_id=customer_id, rep_user_id=scope_rep)
    return [_out(r) for r in branch_scope.visible(current, rows)]


@router.get("/{receipt_id}", response_model=ReceiptOut)
def get_receipt(
    receipt_id: int,
    _: CurrentUser = Depends(require_capability(CAP_COUPON_RECEIVE)),
    db: Session = Depends(get_db),
) -> ReceiptOut:
    try:
        return _out(coupon_receipt_service.get_receipt(db, receipt_id))
    except CouponReceiptError as exc:
        raise HTTPException(404, {"code": "not_found", "message": str(exc)}) from exc
